.TH MIDO3-PLAY 1 "Jul 07, 2016"
.SH NAME
mido3-play \- plays MIDI files
.SH SYNOPSIS
.B mido3-play
.RI " song1-to-play song2-to-play " 
.SH DESCRIPTION
This manual page documents briefly the \fBmido3-play\fR command.
.PP
Plays back one or more MIDI files.
.SH AUTHOR
mido3-play was written by Ole Martin Bjørndalen <ombdalen@gmail.com>
.PP
This manual page was written by Josue Ortega <josue@debian.org>,
for the Debian project (and may be used by others).
