.TH MIDO3-SERVE 1 "Jul 07, 2016"
.SH NAME
mido3-serve \- Serves one or more ports over the network
.SH SYNOPSIS
.B mido3-serve
.RI " :port 'device-name-to-forward-messages'" 
.SH DESCRIPTION
This manual page documents briefly the \fBmido3-serve\fR command.
.PP
Serves one or more ports over the network.
.SH AUTHOR
mido3-serve was written by Ole Martin Bjørndalen <ombdalen@gmail.com>
.PP
This manual page was written by Josue Ortega <josue@debian.org>,
for the Debian project (and may be used by others).
