.TH MIDO3-CONNECT 1 "Jul 07, 2016"
.SH NAME
mido3-connect \- MIDI messages forwarder
.SH SYNOPSIS
.B mido3-connect
.RI " remote-connectr-addres:port 'device-name-sending-messages'" 
.SH DESCRIPTION
This manual page documents briefly the \fBmido3-connect\fR command.
.PP
Forwards all messages that arrive on one or more ports to a server.
.SH AUTHOR
mido3-connect was written by Ole Martin Bjørndalen <ombdalen@gmail.com>
.PP
This manual page was written by Josue Ortega <josue@debian.org>,
for the Debian project (and may be used by others).
