.TH MIDO3-PORTS 1 "Jul 07, 2016"
.SH NAME
mido3-ports \- lists available ports for mido3
.SH DESCRIPTION
This manual page documents briefly the \fBmido3-ports\fR command.
.PP
Lists available input and output ports and shows environment variables and the current backend module.
.SH AUTHOR
mido3-ports was written by Ole Martin Bjørndalen <ombdalen@gmail.com>
.PP
This manual page was written by Josue Ortega <josue@debian.org>,
for the Debian project (and may be used by others).
